language: python
python:
  - "2.7"

sudo: false

#language: node_js
#node_js:
#  - "0.10"

before_install:
#  - npm install -g jshint
  - pip install https://github.com/koenbok/Cactus/archive/master.zip
  - pip install glue
  - wget https://raw.githubusercontent.com/mozilla/html5-lint/master/html5check.py

script:
  - cactus build
  - cd .build 
  - CHECK=$(for file in *.html; do python ../html5check.py -geh $file; done;)
  - if [[ ! -z $(echo "$CHECK" | grep -vE 'index_|iframe') ]]; then echo "$CHECK"; exit 1; fi;
#  - jshint --extract auto *.html
#  - jshint static/js/*.js 
