language: python
python:
  - "3.5"

sudo: false

#language: node_js
#node_js:
#  - "0.10"

before_install:
  # Install Java 8 for validator.nu
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle

install:
#  - npm install -g jshint
  # Install requirements for building the site
  - pip install cactus
  - pip install glue
  - pip install html5validator

script:
  - cactus build
  - html5validator --root .build --show-warnings
#  - jshint --extract auto *.html
#  - jshint static/js/*.js 
