language: python
python:
  - "3.5"

sudo: false

#language: node_js
#node_js:
#  - "0.10"

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_script:
  - nvm install
  - nvm use
  - npm install -g yarn

install:
  # Install requirements for building the site
  - pip install cactus
  - pip install glue
  - pip install html5validator
  - yarn install

script:
  - yarn run stylelint
  - cactus build
  - html5validator --root .build --show-warnings --ignore 'index_'
