language: python
python:
  - "3.5"

sudo: false

#language: node_js
#node_js:
#  - "0.10"

addons:
  apt:
    packages:
      - oracle-java8-set-default

install:
#  - npm install -g jshint
  # Install requirements for building the site
  - pip install cactus
  - pip install glue
  - pip install html5validator

script:
  - cactus build
  - html5validator --root .build --show-warnings
#  - jshint --extract auto *.html
#  - jshint static/js/*.js 
