services:
  pelican:
    image: 'ghcr.io/astral-sh/uv:debian'
    restart: unless-stopped
    volumes:
      - '.:/base'
    working_dir: '/base'
    command: "uvx --from 'rust-just' just serve"
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
