services:
  pelican-build:
    image: 'ghcr.io/astral-sh/uv:debian'
    restart: 'no'
    volumes:
      - '.:/base'
    working_dir: '/base'
    command: 'make build'
    stdin_open: true
    tty: true
