version: '3.7'

services:
  pelican-build:
    image: 'python:3.13'
    restart: 'no'
    volumes:
      - '.:/base'
    working_dir: '/base'
    command: 'make build'
    stdin_open: true
    tty: true
