version: '3.7'
services:

  pelican:
    image: 'python:3.10'
    restart: unless-stopped
    volumes:
      - '.:/base'
    ports:
      - '8000:8000'
    working_dir: '/base'
    command: 'make serve'
    stdin_open: true
    tty: true
