name: Build site and check output

on:
  schedule:
    - cron: '0 6 1,15 * 5'
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build site
      run: |
        pelican
    - name: Check html
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: .build/
        css: true
        log_level: INFO
        extra: --ignore index_

