name: Build site and check output

on:
  schedule:
    - cron: '0 6 1,15 * 5'
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: make install
      - run: make build
      - uses: Cyb3r-Jak3/html5validator-action@v0.6.1
        with:
          root: .build/
          css: true
          log_level: INFO
          blacklist: index_footer.html index_header.html
