name: Build site and check output

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: dubnium
    - name: Install openjdk
      run: |
        sudo apt-get install openjdk-8-jre
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install html5validator
    - name: Install Node dependencies
      run: |
        npm i
    - name: Build site
      run: |
        cactus build
    - name: Check html
      run: |
        html5validator --root .build --show-warnings --ignore 'index_' --also-check-css

